name: Node.js CI with Static Analysis

on:
  [push]
 

env:
  NODE_ENV: production

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: stefanoeb/eslint-action@1.0.2
        with:
          files: telegram_api/
